// Feature Components
export { QuickCapture } from './QuickCapture'
export { AISuggestions } from './AISuggestions'
export { DailyBriefing } from './DailyBriefing'
export { SmartTaskList } from './SmartTaskList'
export { NotificationPrompt } from './NotificationPrompt'
export { RecurrencePicker, getRecurrenceDescription, getNextOccurrence } from './RecurrencePicker'
export type { RecurrencePattern, RecurrenceConfig } from './RecurrencePicker'
export { TaskComments } from './TaskComments'
export type { Comment } from './TaskComments'
export { HabitTracker } from './HabitTracker'
export type { Habit } from './HabitTracker'
export { WidgetDashboard } from './WidgetDashboard'
export { SmartInput } from './SmartInput'
export { AddTaskDialog } from './AddTaskDialog'
export { ProductivityCharts } from './ProductivityCharts'
export { CompletionHeatmap } from './CompletionHeatmap'
export { TaskItem } from './TaskItem'
